
name: Build Pipeline

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'

jobs:
    build:
        name: Build Application
        runs-on: ubuntu-latest
        steps:
           - name: Git Checkout
             uses: actions/checkout@v3
           
           - name: Install Node 
             uses: actions/setup-node@v3
             with:
                node-version: 16

           - name: Install React Package
             run: npm i react-scripts
             
           - name: Building project
             run: npm run build

           - name: Running tests
             run: npm run test

           - name: Uploading production-ready build files
             uses: actions/upload-artifact@v2
             with:
                name: production-files
                path: ./build